---
- name: Copy config files with ldap enabled
  hosts: localhost
  vars_files:
    - vars/vars.yml
  any_errors_fatal: true
  remote_user: root 
  become: yes
  become_method: su
  tasks:
  - name: Copy file nsswitch with owner and permissions
    template:
      src: template/nsswitch.conf.j2
      dest: /etc/nsswitch.conf
      owner: root
      group: root
      mode: '0644'
  - name: Copy file ldap.conf with owner and permissions
    template:
      src: template/ldap.conf.j2
      dest: /etc/ldap/ldap.conf
      owner: root
      group: root
      mode: '0644'
  - name: Copy file sldap.conf with owner and permissions
    template:
      src: template/slapd.conf.j2
      dest: /usr/share/slapd/slapd.conf
      owner: root
      group: root
      mode: '0644'
  - name: Copy file krb5.conf with new ldap settings
    template:
      src: template/krb5.conf.ldap.j2
      dest: /etc/krb5.conf
      owner: root
      group: root
      mode: '0644'
  - name: Copy file kdc.conf with new ldap settings
    template:
      src: template/kdc.conf.ldap.j2
      dest: /etc/krb5kdc/kdc.conf
      owner: root
      group: root
      mode: '0644'
  - name: Reload configs
    systemd: daemon_reload=yes

