---
- name: Install kerberose on raspberry Pi
  hosts: localhost
  any_errors_fatal: true
  remote_user: root
  become: yes
  become_method: su
  tasks:  
  - name: Set timezone to America/Toronto
    timezone:
      name: America/Toronto
  - name: Set hostname
    hostname: 
      name: kdc.home.com
  - name: Update & upgrade all packages to the latest version
    apt:
      upgrade: yes
      update_cache: yes
      force_apt_get: yes #Needed for Raspbian(buster) 
      cache_valid_time: 86400 #One day
  - name: Install kerberose server packages
    apt:
      pkg: 
      - krb5-kdc
      - krb5-admin-server
      - krb5-config
  - name: Copy file krb5.conf with owner and permissions
    copy:
      src: config/krb5.conf
      dest: /etc/krb5.conf
      owner: root
      group: root
      mode: '0644'
  - name: Copy file kadm5.acl with owner and permissions
    copy:
      src: config/kadm5.acl
      dest: /etc/krb5kdc/kadm5.acl
      owner: root
      group: root
      mode: '0644'
  - name: Copy ssh client config
    copy:
      src: config/ssh_config
      dest: /etc/ssh/ssh_config
      owner: root
      group: root
      mode: '0644'
  - name: Copy ssh daemon config
    copy:
      src: config/sshd_config
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: '0644'
  - name: Create the initial kerberos database
    script: createKerberoseDB.sh  
  - name: start KDC service
    service:
      name: krb5-kdc 
      state: restarted 
      enabled: yes
  - name: start admin server 
    service:
      name: krb5-admin-server 
      state: restarted 
      enabled: yes
